services:
  bestsub:
    image: ghcr.io/bestruirui/bestsub:latest
    container_name: bestsub
    restart: unless-stopped
    ports:
      - "8080:8080"
    volumes:
      - ./data:/app/data
    depends_on:
      - minisubconvert

  minisubconvert:
    image: ghcr.io/bestruirui/minisubconvert:latest
    container_name: minisubconvert
    restart: unless-stopped
    environment:
      - SECRET=minisubconvert
      - PORT=3000
    ports:
      - "3000:3000"
