export type CountryOption = { // 国家多选框使用的展示与提交数据。
    id: string; // ISO 3166-1 alpha-2 国家代码。
    nameEn: string; // 英文名称。
    nameZh: string; // 中文名称。
};

export const countryOptions: CountryOption[] = [ // 按国家代码稳定排序的候选项。
    { id: "AD", nameEn: "Andorra", nameZh: "安道尔" },
    { id: "AE", nameEn: "United Arab Emirates", nameZh: "阿拉伯联合酋长国" },
    { id: "AF", nameEn: "Afghanistan", nameZh: "阿富汗" },
    { id: "AG", nameEn: "Antigua and Barbuda", nameZh: "安提瓜和巴布达" },
    { id: "AI", nameEn: "Anguilla", nameZh: "安圭拉" },
    { id: "AL", nameEn: "Albania", nameZh: "阿尔巴尼亚" },
    { id: "AM", nameEn: "Armenia", nameZh: "亚美尼亚" },
    { id: "AO", nameEn: "Angola", nameZh: "安哥拉" },
    { id: "AQ", nameEn: "Antarctica", nameZh: "南极洲" },
    { id: "AR", nameEn: "Argentina", nameZh: "阿根廷" },
    { id: "AS", nameEn: "American Samoa", nameZh: "美属萨摩亚" },
    { id: "AT", nameEn: "Austria", nameZh: "奥地利" },
    { id: "AU", nameEn: "Australia", nameZh: "澳大利亚" },
    { id: "AW", nameEn: "Aruba", nameZh: "阿鲁巴" },
    { id: "AX", nameEn: "Aland Islands", nameZh: "奥兰群岛" },
    { id: "AZ", nameEn: "Azerbaijan", nameZh: "阿塞拜疆" },
    { id: "BA", nameEn: "Bosnia and Herzegovina", nameZh: "波斯尼亚和黑塞哥维那" },
    { id: "BB", nameEn: "Barbados", nameZh: "巴巴多斯" },
    { id: "BD", nameEn: "Bangladesh", nameZh: "孟加拉国" },
    { id: "BE", nameEn: "Belgium", nameZh: "比利时" },
    { id: "BF", nameEn: "Burkina Faso", nameZh: "布基纳法索" },
    { id: "BG", nameEn: "Bulgaria", nameZh: "保加利亚" },
    { id: "BH", nameEn: "Bahrain", nameZh: "巴林" },
    { id: "BI", nameEn: "Burundi", nameZh: "布隆迪" },
    { id: "BJ", nameEn: "Benin", nameZh: "贝宁" },
    { id: "BL", nameEn: "Saint Barthelemy", nameZh: "圣巴泰勒米" },
    { id: "BM", nameEn: "Bermuda", nameZh: "百慕大" },
    { id: "BN", nameEn: "Brunei", nameZh: "文莱" },
    { id: "BO", nameEn: "Bolivia", nameZh: "玻利维亚" },
    { id: "BQ", nameEn: "Caribbean Netherlands", nameZh: "荷蘭加勒比區" },
    { id: "BR", nameEn: "Brazil", nameZh: "巴西" },
    { id: "BS", nameEn: "Bahamas", nameZh: "巴哈马" },
    { id: "BT", nameEn: "Bhutan", nameZh: "不丹" },
    { id: "BV", nameEn: "Bouvet Island", nameZh: "布维岛" },
    { id: "BW", nameEn: "Botswana", nameZh: "博茨瓦纳" },
    { id: "BY", nameEn: "Belarus", nameZh: "白俄罗斯" },
    { id: "BZ", nameEn: "Belize", nameZh: "伯利兹" },
    { id: "CA", nameEn: "Canada", nameZh: "加拿大" },
    { id: "CC", nameEn: "Cocos (Keeling) Islands", nameZh: "科科斯" },
    { id: "CD", nameEn: "DR Congo", nameZh: "民主刚果" },
    { id: "CF", nameEn: "Central African Republic", nameZh: "中非共和国" },
    { id: "CG", nameEn: "Congo", nameZh: "刚果" },
    { id: "CH", nameEn: "Switzerland", nameZh: "瑞士" },
    { id: "CI", nameEn: "Ivory Coast", nameZh: "科特迪瓦" },
    { id: "CK", nameEn: "Cook Islands", nameZh: "库克群岛" },
    { id: "CL", nameEn: "Chile", nameZh: "智利" },
    { id: "CM", nameEn: "Cameroon", nameZh: "喀麦隆" },
    { id: "CN", nameEn: "China", nameZh: "中国" },
    { id: "CO", nameEn: "Colombia", nameZh: "哥伦比亚" },
    { id: "CR", nameEn: "Costa Rica", nameZh: "哥斯达黎加" },
    { id: "CU", nameEn: "Cuba", nameZh: "古巴" },
    { id: "CV", nameEn: "Cape Verde", nameZh: "佛得角" },
    { id: "CW", nameEn: "Curacao", nameZh: "库拉索" },
    { id: "CX", nameEn: "Christmas Island", nameZh: "圣诞岛" },
    { id: "CY", nameEn: "Cyprus", nameZh: "塞浦路斯" },
    { id: "CZ", nameEn: "Czechia", nameZh: "捷克" },
    { id: "DE", nameEn: "Germany", nameZh: "德国" },
    { id: "DJ", nameEn: "Djibouti", nameZh: "吉布提" },
    { id: "DK", nameEn: "Denmark", nameZh: "丹麦" },
    { id: "DM", nameEn: "Dominica", nameZh: "多米尼加" },
    { id: "DO", nameEn: "Dominican Republic", nameZh: "多明尼加" },
    { id: "DZ", nameEn: "Algeria", nameZh: "阿尔及利亚" },
    { id: "EC", nameEn: "Ecuador", nameZh: "厄瓜多尔" },
    { id: "EE", nameEn: "Estonia", nameZh: "爱沙尼亚" },
    { id: "EG", nameEn: "Egypt", nameZh: "埃及" },
    { id: "EH", nameEn: "Western Sahara", nameZh: "西撒哈拉" },
    { id: "ER", nameEn: "Eritrea", nameZh: "厄立特里亚" },
    { id: "ES", nameEn: "Spain", nameZh: "西班牙" },
    { id: "ET", nameEn: "Ethiopia", nameZh: "埃塞俄比亚" },
    { id: "FI", nameEn: "Finland", nameZh: "芬兰" },
    { id: "FJ", nameEn: "Fiji", nameZh: "斐济" },
    { id: "FK", nameEn: "Falkland Islands", nameZh: "福克兰群岛" },
    { id: "FM", nameEn: "Micronesia", nameZh: "密克罗尼西亚" },
    { id: "FO", nameEn: "Faroe Islands", nameZh: "法罗群岛" },
    { id: "FR", nameEn: "France", nameZh: "法国" },
    { id: "GA", nameEn: "Gabon", nameZh: "加蓬" },
    { id: "GB", nameEn: "United Kingdom", nameZh: "英国" },
    { id: "GD", nameEn: "Grenada", nameZh: "格林纳达" },
    { id: "GE", nameEn: "Georgia", nameZh: "格鲁吉亚" },
    { id: "GF", nameEn: "French Guiana", nameZh: "法属圭亚那" },
    { id: "GG", nameEn: "Guernsey", nameZh: "根西岛" },
    { id: "GH", nameEn: "Ghana", nameZh: "加纳" },
    { id: "GI", nameEn: "Gibraltar", nameZh: "直布罗陀" },
    { id: "GL", nameEn: "Greenland", nameZh: "格陵兰" },
    { id: "GM", nameEn: "Gambia", nameZh: "冈比亚" },
    { id: "GN", nameEn: "Guinea", nameZh: "几内亚" },
    { id: "GP", nameEn: "Guadeloupe", nameZh: "瓜德罗普岛" },
    { id: "GQ", nameEn: "Equatorial Guinea", nameZh: "赤道几内亚" },
    { id: "GR", nameEn: "Greece", nameZh: "希腊" },
    { id: "GS", nameEn: "South Georgia", nameZh: "南乔治亚" },
    { id: "GT", nameEn: "Guatemala", nameZh: "危地马拉" },
    { id: "GU", nameEn: "Guam", nameZh: "关岛" },
    { id: "GW", nameEn: "Guinea-Bissau", nameZh: "几内亚比绍" },
    { id: "GY", nameEn: "Guyana", nameZh: "圭亚那" },
    { id: "HK", nameEn: "Hong Kong", nameZh: "香港" },
    { id: "HM", nameEn: "Heard Island and McDonald Islands", nameZh: "赫德岛和麦当劳群岛" },
    { id: "HN", nameEn: "Honduras", nameZh: "洪都拉斯" },
    { id: "HR", nameEn: "Croatia", nameZh: "克罗地亚" },
    { id: "HT", nameEn: "Haiti", nameZh: "海地" },
    { id: "HU", nameEn: "Hungary", nameZh: "匈牙利" },
    { id: "ID", nameEn: "Indonesia", nameZh: "印度尼西亚" },
    { id: "IE", nameEn: "Ireland", nameZh: "爱尔兰" },
    { id: "IL", nameEn: "Israel", nameZh: "以色列" },
    { id: "IM", nameEn: "Isle of Man", nameZh: "马恩岛" },
    { id: "IN", nameEn: "India", nameZh: "印度" },
    { id: "IO", nameEn: "British Indian Ocean Territory", nameZh: "英属印度洋领地" },
    { id: "IQ", nameEn: "Iraq", nameZh: "伊拉克" },
    { id: "IR", nameEn: "Iran", nameZh: "伊朗" },
    { id: "IS", nameEn: "Iceland", nameZh: "冰岛" },
    { id: "IT", nameEn: "Italy", nameZh: "意大利" },
    { id: "JE", nameEn: "Jersey", nameZh: "泽西岛" },
    { id: "JM", nameEn: "Jamaica", nameZh: "牙买加" },
    { id: "JO", nameEn: "Jordan", nameZh: "约旦" },
    { id: "JP", nameEn: "Japan", nameZh: "日本" },
    { id: "KE", nameEn: "Kenya", nameZh: "肯尼亚" },
    { id: "KG", nameEn: "Kyrgyzstan", nameZh: "吉尔吉斯斯坦" },
    { id: "KH", nameEn: "Cambodia", nameZh: "柬埔寨" },
    { id: "KI", nameEn: "Kiribati", nameZh: "基里巴斯" },
    { id: "KM", nameEn: "Comoros", nameZh: "科摩罗" },
    { id: "KN", nameEn: "Saint Kitts and Nevis", nameZh: "圣基茨和尼维斯" },
    { id: "KP", nameEn: "North Korea", nameZh: "朝鲜" },
    { id: "KR", nameEn: "South Korea", nameZh: "韩国" },
    { id: "KW", nameEn: "Kuwait", nameZh: "科威特" },
    { id: "KY", nameEn: "Cayman Islands", nameZh: "开曼群岛" },
    { id: "KZ", nameEn: "Kazakhstan", nameZh: "哈萨克斯坦" },
    { id: "LA", nameEn: "Laos", nameZh: "老挝" },
    { id: "LB", nameEn: "Lebanon", nameZh: "黎巴嫩" },
    { id: "LC", nameEn: "Saint Lucia", nameZh: "圣卢西亚" },
    { id: "LI", nameEn: "Liechtenstein", nameZh: "列支敦士登" },
    { id: "LK", nameEn: "Sri Lanka", nameZh: "斯里兰卡" },
    { id: "LR", nameEn: "Liberia", nameZh: "利比里亚" },
    { id: "LS", nameEn: "Lesotho", nameZh: "莱索托" },
    { id: "LT", nameEn: "Lithuania", nameZh: "立陶宛" },
    { id: "LU", nameEn: "Luxembourg", nameZh: "卢森堡" },
    { id: "LV", nameEn: "Latvia", nameZh: "拉脱维亚" },
    { id: "LY", nameEn: "Libya", nameZh: "利比亚" },
    { id: "MA", nameEn: "Morocco", nameZh: "摩洛哥" },
    { id: "MC", nameEn: "Monaco", nameZh: "摩纳哥" },
    { id: "MD", nameEn: "Moldova", nameZh: "摩尔多瓦" },
    { id: "ME", nameEn: "Montenegro", nameZh: "黑山" },
    { id: "MF", nameEn: "Saint Martin", nameZh: "圣马丁" },
    { id: "MG", nameEn: "Madagascar", nameZh: "马达加斯加" },
    { id: "MH", nameEn: "Marshall Islands", nameZh: "马绍尔群岛" },
    { id: "MK", nameEn: "North Macedonia", nameZh: "北馬其頓" },
    { id: "ML", nameEn: "Mali", nameZh: "马里" },
    { id: "MM", nameEn: "Myanmar", nameZh: "缅甸" },
    { id: "MN", nameEn: "Mongolia", nameZh: "蒙古" },
    { id: "MO", nameEn: "Macau", nameZh: "澳门" },
    { id: "MP", nameEn: "Northern Mariana Islands", nameZh: "北马里亚纳群岛" },
    { id: "MQ", nameEn: "Martinique", nameZh: "马提尼克" },
    { id: "MR", nameEn: "Mauritania", nameZh: "毛里塔尼亚" },
    { id: "MS", nameEn: "Montserrat", nameZh: "蒙特塞拉特" },
    { id: "MT", nameEn: "Malta", nameZh: "马耳他" },
    { id: "MU", nameEn: "Mauritius", nameZh: "毛里求斯" },
    { id: "MV", nameEn: "Maldives", nameZh: "马尔代夫" },
    { id: "MW", nameEn: "Malawi", nameZh: "马拉维" },
    { id: "MX", nameEn: "Mexico", nameZh: "墨西哥" },
    { id: "MY", nameEn: "Malaysia", nameZh: "马来西亚" },
    { id: "MZ", nameEn: "Mozambique", nameZh: "莫桑比克" },
    { id: "NA", nameEn: "Namibia", nameZh: "纳米比亚" },
    { id: "NC", nameEn: "New Caledonia", nameZh: "新喀里多尼亚" },
    { id: "NE", nameEn: "Niger", nameZh: "尼日尔" },
    { id: "NF", nameEn: "Norfolk Island", nameZh: "诺福克岛" },
    { id: "NG", nameEn: "Nigeria", nameZh: "尼日利亚" },
    { id: "NI", nameEn: "Nicaragua", nameZh: "尼加拉瓜" },
    { id: "NL", nameEn: "Netherlands", nameZh: "荷兰" },
    { id: "NO", nameEn: "Norway", nameZh: "挪威" },
    { id: "NP", nameEn: "Nepal", nameZh: "尼泊尔" },
    { id: "NR", nameEn: "Nauru", nameZh: "瑙鲁" },
    { id: "NU", nameEn: "Niue", nameZh: "纽埃" },
    { id: "NZ", nameEn: "New Zealand", nameZh: "新西兰" },
    { id: "OM", nameEn: "Oman", nameZh: "阿曼" },
    { id: "PA", nameEn: "Panama", nameZh: "巴拿马" },
    { id: "PE", nameEn: "Peru", nameZh: "秘鲁" },
    { id: "PF", nameEn: "French Polynesia", nameZh: "法属波利尼西亚" },
    { id: "PG", nameEn: "Papua New Guinea", nameZh: "巴布亚新几内亚" },
    { id: "PH", nameEn: "Philippines", nameZh: "菲律宾" },
    { id: "PK", nameEn: "Pakistan", nameZh: "巴基斯坦" },
    { id: "PL", nameEn: "Poland", nameZh: "波兰" },
    { id: "PM", nameEn: "Saint Pierre and Miquelon", nameZh: "圣皮埃尔和密克隆" },
    { id: "PN", nameEn: "Pitcairn Islands", nameZh: "皮特凯恩群岛" },
    { id: "PR", nameEn: "Puerto Rico", nameZh: "波多黎各" },
    { id: "PS", nameEn: "Palestine", nameZh: "巴勒斯坦" },
    { id: "PT", nameEn: "Portugal", nameZh: "葡萄牙" },
    { id: "PW", nameEn: "Palau", nameZh: "帕劳" },
    { id: "PY", nameEn: "Paraguay", nameZh: "巴拉圭" },
    { id: "QA", nameEn: "Qatar", nameZh: "卡塔尔" },
    { id: "RE", nameEn: "Reunion", nameZh: "留尼旺岛" },
    { id: "RO", nameEn: "Romania", nameZh: "罗马尼亚" },
    { id: "RS", nameEn: "Serbia", nameZh: "塞尔维亚" },
    { id: "RU", nameEn: "Russia", nameZh: "俄罗斯" },
    { id: "RW", nameEn: "Rwanda", nameZh: "卢旺达" },
    { id: "SA", nameEn: "Saudi Arabia", nameZh: "沙特阿拉伯" },
    { id: "SB", nameEn: "Solomon Islands", nameZh: "所罗门群岛" },
    { id: "SC", nameEn: "Seychelles", nameZh: "塞舌尔" },
    { id: "SD", nameEn: "Sudan", nameZh: "苏丹" },
    { id: "SE", nameEn: "Sweden", nameZh: "瑞典" },
    { id: "SG", nameEn: "Singapore", nameZh: "新加坡" },
    { id: "SH", nameEn: "Saint Helena, Ascension and Tristan da Cunha", nameZh: "圣赫勒拿、阿森松和特里斯坦-达库尼亚" },
    { id: "SI", nameEn: "Slovenia", nameZh: "斯洛文尼亚" },
    { id: "SJ", nameEn: "Svalbard and Jan Mayen", nameZh: "斯瓦尔巴特" },
    { id: "SK", nameEn: "Slovakia", nameZh: "斯洛伐克" },
    { id: "SL", nameEn: "Sierra Leone", nameZh: "塞拉利昂" },
    { id: "SM", nameEn: "San Marino", nameZh: "圣马力诺" },
    { id: "SN", nameEn: "Senegal", nameZh: "塞内加尔" },
    { id: "SO", nameEn: "Somalia", nameZh: "索马里" },
    { id: "SR", nameEn: "Suriname", nameZh: "苏里南" },
    { id: "SS", nameEn: "South Sudan", nameZh: "南苏丹" },
    { id: "ST", nameEn: "Sao Tome and Principe", nameZh: "圣多美和普林西比" },
    { id: "SV", nameEn: "El Salvador", nameZh: "萨尔瓦多" },
    { id: "SX", nameEn: "Sint Maarten", nameZh: "圣马丁岛" },
    { id: "SY", nameEn: "Syria", nameZh: "叙利亚" },
    { id: "SZ", nameEn: "Eswatini", nameZh: "斯威士兰" },
    { id: "TC", nameEn: "Turks and Caicos Islands", nameZh: "特克斯和凯科斯群岛" },
    { id: "TD", nameEn: "Chad", nameZh: "乍得" },
    { id: "TF", nameEn: "French Southern and Antarctic Lands", nameZh: "法国南部和南极土地" },
    { id: "TG", nameEn: "Togo", nameZh: "多哥" },
    { id: "TH", nameEn: "Thailand", nameZh: "泰国" },
    { id: "TJ", nameEn: "Tajikistan", nameZh: "塔吉克斯坦" },
    { id: "TK", nameEn: "Tokelau", nameZh: "托克劳" },
    { id: "TL", nameEn: "Timor-Leste", nameZh: "东帝汶" },
    { id: "TM", nameEn: "Turkmenistan", nameZh: "土库曼斯坦" },
    { id: "TN", nameEn: "Tunisia", nameZh: "突尼斯" },
    { id: "TO", nameEn: "Tonga", nameZh: "汤加" },
    { id: "TR", nameEn: "Turkiye", nameZh: "土耳其" },
    { id: "TT", nameEn: "Trinidad and Tobago", nameZh: "特立尼达和多巴哥" },
    { id: "TV", nameEn: "Tuvalu", nameZh: "图瓦卢" },
    { id: "TW", nameEn: "Taiwan", nameZh: "台灣" },
    { id: "TZ", nameEn: "Tanzania", nameZh: "坦桑尼亚" },
    { id: "UA", nameEn: "Ukraine", nameZh: "乌克兰" },
    { id: "UG", nameEn: "Uganda", nameZh: "乌干达" },
    { id: "UM", nameEn: "United States Minor Outlying Islands", nameZh: "美国本土外小岛屿" },
    { id: "US", nameEn: "United States", nameZh: "美国" },
    { id: "UY", nameEn: "Uruguay", nameZh: "乌拉圭" },
    { id: "UZ", nameEn: "Uzbekistan", nameZh: "乌兹别克斯坦" },
    { id: "VA", nameEn: "Vatican City", nameZh: "梵蒂冈" },
    { id: "VC", nameEn: "Saint Vincent and the Grenadines", nameZh: "圣文森特和格林纳丁斯" },
    { id: "VE", nameEn: "Venezuela", nameZh: "委内瑞拉" },
    { id: "VG", nameEn: "British Virgin Islands", nameZh: "英属维尔京群岛" },
    { id: "VI", nameEn: "United States Virgin Islands", nameZh: "美属维尔京群岛" },
    { id: "VN", nameEn: "Vietnam", nameZh: "越南" },
    { id: "VU", nameEn: "Vanuatu", nameZh: "瓦努阿图" },
    { id: "WF", nameEn: "Wallis and Futuna", nameZh: "瓦利斯和富图纳群岛" },
    { id: "WS", nameEn: "Samoa", nameZh: "萨摩亚" },
    { id: "XK", nameEn: "Kosovo", nameZh: "科索沃" },
    { id: "YE", nameEn: "Yemen", nameZh: "也门" },
    { id: "YT", nameEn: "Mayotte", nameZh: "马约特" },
    { id: "ZA", nameEn: "South Africa", nameZh: "南非" },
    { id: "ZM", nameEn: "Zambia", nameZh: "赞比亚" },
    { id: "ZW", nameEn: "Zimbabwe", nameZh: "津巴布韦" },
];
