package countries

import "strings"

type Country struct {
	Alpha2 string // ISO 3166-1 alpha-2 国家代码。
	NameEn string // 英文名称。
	NameZh string // 中文名称。
	Flag   string // 区域指示符旗帜 emoji。
}

type countryName struct {
	NameEn string
	NameZh string
}

func Get(code string) Country {
	code = strings.ToUpper(code)
	country, ok := names[code]
	if !ok {
		return Country{}
	}
	return Country{
		Alpha2: code,
		NameEn: country.NameEn,
		NameZh: country.NameZh,
		Flag:   string([]rune{rune(code[0]) + 127397, rune(code[1]) + 127397}),
	}
}

var names = map[string]countryName{
	"AD": {NameEn: "Andorra", NameZh: "安道尔"},
	"AE": {NameEn: "United Arab Emirates", NameZh: "阿拉伯联合酋长国"},
	"AF": {NameEn: "Afghanistan", NameZh: "阿富汗"},
	"AG": {NameEn: "Antigua and Barbuda", NameZh: "安提瓜和巴布达"},
	"AI": {NameEn: "Anguilla", NameZh: "安圭拉"},
	"AL": {NameEn: "Albania", NameZh: "阿尔巴尼亚"},
	"AM": {NameEn: "Armenia", NameZh: "亚美尼亚"},
	"AO": {NameEn: "Angola", NameZh: "安哥拉"},
	"AQ": {NameEn: "Antarctica", NameZh: "南极洲"},
	"AR": {NameEn: "Argentina", NameZh: "阿根廷"},
	"AS": {NameEn: "American Samoa", NameZh: "美属萨摩亚"},
	"AT": {NameEn: "Austria", NameZh: "奥地利"},
	"AU": {NameEn: "Australia", NameZh: "澳大利亚"},
	"AW": {NameEn: "Aruba", NameZh: "阿鲁巴"},
	"AX": {NameEn: "Aland Islands", NameZh: "奥兰群岛"},
	"AZ": {NameEn: "Azerbaijan", NameZh: "阿塞拜疆"},
	"BA": {NameEn: "Bosnia and Herzegovina", NameZh: "波斯尼亚和黑塞哥维那"},
	"BB": {NameEn: "Barbados", NameZh: "巴巴多斯"},
	"BD": {NameEn: "Bangladesh", NameZh: "孟加拉国"},
	"BE": {NameEn: "Belgium", NameZh: "比利时"},
	"BF": {NameEn: "Burkina Faso", NameZh: "布基纳法索"},
	"BG": {NameEn: "Bulgaria", NameZh: "保加利亚"},
	"BH": {NameEn: "Bahrain", NameZh: "巴林"},
	"BI": {NameEn: "Burundi", NameZh: "布隆迪"},
	"BJ": {NameEn: "Benin", NameZh: "贝宁"},
	"BL": {NameEn: "Saint Barthelemy", NameZh: "圣巴泰勒米"},
	"BM": {NameEn: "Bermuda", NameZh: "百慕大"},
	"BN": {NameEn: "Brunei", NameZh: "文莱"},
	"BO": {NameEn: "Bolivia", NameZh: "玻利维亚"},
	"BQ": {NameEn: "Caribbean Netherlands", NameZh: "荷蘭加勒比區"},
	"BR": {NameEn: "Brazil", NameZh: "巴西"},
	"BS": {NameEn: "Bahamas", NameZh: "巴哈马"},
	"BT": {NameEn: "Bhutan", NameZh: "不丹"},
	"BV": {NameEn: "Bouvet Island", NameZh: "布维岛"},
	"BW": {NameEn: "Botswana", NameZh: "博茨瓦纳"},
	"BY": {NameEn: "Belarus", NameZh: "白俄罗斯"},
	"BZ": {NameEn: "Belize", NameZh: "伯利兹"},
	"CA": {NameEn: "Canada", NameZh: "加拿大"},
	"CC": {NameEn: "Cocos (Keeling) Islands", NameZh: "科科斯"},
	"CD": {NameEn: "DR Congo", NameZh: "民主刚果"},
	"CF": {NameEn: "Central African Republic", NameZh: "中非共和国"},
	"CG": {NameEn: "Congo", NameZh: "刚果"},
	"CH": {NameEn: "Switzerland", NameZh: "瑞士"},
	"CI": {NameEn: "Ivory Coast", NameZh: "科特迪瓦"},
	"CK": {NameEn: "Cook Islands", NameZh: "库克群岛"},
	"CL": {NameEn: "Chile", NameZh: "智利"},
	"CM": {NameEn: "Cameroon", NameZh: "喀麦隆"},
	"CN": {NameEn: "China", NameZh: "中国"},
	"CO": {NameEn: "Colombia", NameZh: "哥伦比亚"},
	"CR": {NameEn: "Costa Rica", NameZh: "哥斯达黎加"},
	"CU": {NameEn: "Cuba", NameZh: "古巴"},
	"CV": {NameEn: "Cape Verde", NameZh: "佛得角"},
	"CW": {NameEn: "Curacao", NameZh: "库拉索"},
	"CX": {NameEn: "Christmas Island", NameZh: "圣诞岛"},
	"CY": {NameEn: "Cyprus", NameZh: "塞浦路斯"},
	"CZ": {NameEn: "Czechia", NameZh: "捷克"},
	"DE": {NameEn: "Germany", NameZh: "德国"},
	"DJ": {NameEn: "Djibouti", NameZh: "吉布提"},
	"DK": {NameEn: "Denmark", NameZh: "丹麦"},
	"DM": {NameEn: "Dominica", NameZh: "多米尼加"},
	"DO": {NameEn: "Dominican Republic", NameZh: "多明尼加"},
	"DZ": {NameEn: "Algeria", NameZh: "阿尔及利亚"},
	"EC": {NameEn: "Ecuador", NameZh: "厄瓜多尔"},
	"EE": {NameEn: "Estonia", NameZh: "爱沙尼亚"},
	"EG": {NameEn: "Egypt", NameZh: "埃及"},
	"EH": {NameEn: "Western Sahara", NameZh: "西撒哈拉"},
	"ER": {NameEn: "Eritrea", NameZh: "厄立特里亚"},
	"ES": {NameEn: "Spain", NameZh: "西班牙"},
	"ET": {NameEn: "Ethiopia", NameZh: "埃塞俄比亚"},
	"FI": {NameEn: "Finland", NameZh: "芬兰"},
	"FJ": {NameEn: "Fiji", NameZh: "斐济"},
	"FK": {NameEn: "Falkland Islands", NameZh: "福克兰群岛"},
	"FM": {NameEn: "Micronesia", NameZh: "密克罗尼西亚"},
	"FO": {NameEn: "Faroe Islands", NameZh: "法罗群岛"},
	"FR": {NameEn: "France", NameZh: "法国"},
	"GA": {NameEn: "Gabon", NameZh: "加蓬"},
	"GB": {NameEn: "United Kingdom", NameZh: "英国"},
	"GD": {NameEn: "Grenada", NameZh: "格林纳达"},
	"GE": {NameEn: "Georgia", NameZh: "格鲁吉亚"},
	"GF": {NameEn: "French Guiana", NameZh: "法属圭亚那"},
	"GG": {NameEn: "Guernsey", NameZh: "根西岛"},
	"GH": {NameEn: "Ghana", NameZh: "加纳"},
	"GI": {NameEn: "Gibraltar", NameZh: "直布罗陀"},
	"GL": {NameEn: "Greenland", NameZh: "格陵兰"},
	"GM": {NameEn: "Gambia", NameZh: "冈比亚"},
	"GN": {NameEn: "Guinea", NameZh: "几内亚"},
	"GP": {NameEn: "Guadeloupe", NameZh: "瓜德罗普岛"},
	"GQ": {NameEn: "Equatorial Guinea", NameZh: "赤道几内亚"},
	"GR": {NameEn: "Greece", NameZh: "希腊"},
	"GS": {NameEn: "South Georgia", NameZh: "南乔治亚"},
	"GT": {NameEn: "Guatemala", NameZh: "危地马拉"},
	"GU": {NameEn: "Guam", NameZh: "关岛"},
	"GW": {NameEn: "Guinea-Bissau", NameZh: "几内亚比绍"},
	"GY": {NameEn: "Guyana", NameZh: "圭亚那"},
	"HK": {NameEn: "Hong Kong", NameZh: "香港"},
	"HM": {NameEn: "Heard Island and McDonald Islands", NameZh: "赫德岛和麦当劳群岛"},
	"HN": {NameEn: "Honduras", NameZh: "洪都拉斯"},
	"HR": {NameEn: "Croatia", NameZh: "克罗地亚"},
	"HT": {NameEn: "Haiti", NameZh: "海地"},
	"HU": {NameEn: "Hungary", NameZh: "匈牙利"},
	"ID": {NameEn: "Indonesia", NameZh: "印度尼西亚"},
	"IE": {NameEn: "Ireland", NameZh: "爱尔兰"},
	"IL": {NameEn: "Israel", NameZh: "以色列"},
	"IM": {NameEn: "Isle of Man", NameZh: "马恩岛"},
	"IN": {NameEn: "India", NameZh: "印度"},
	"IO": {NameEn: "British Indian Ocean Territory", NameZh: "英属印度洋领地"},
	"IQ": {NameEn: "Iraq", NameZh: "伊拉克"},
	"IR": {NameEn: "Iran", NameZh: "伊朗"},
	"IS": {NameEn: "Iceland", NameZh: "冰岛"},
	"IT": {NameEn: "Italy", NameZh: "意大利"},
	"JE": {NameEn: "Jersey", NameZh: "泽西岛"},
	"JM": {NameEn: "Jamaica", NameZh: "牙买加"},
	"JO": {NameEn: "Jordan", NameZh: "约旦"},
	"JP": {NameEn: "Japan", NameZh: "日本"},
	"KE": {NameEn: "Kenya", NameZh: "肯尼亚"},
	"KG": {NameEn: "Kyrgyzstan", NameZh: "吉尔吉斯斯坦"},
	"KH": {NameEn: "Cambodia", NameZh: "柬埔寨"},
	"KI": {NameEn: "Kiribati", NameZh: "基里巴斯"},
	"KM": {NameEn: "Comoros", NameZh: "科摩罗"},
	"KN": {NameEn: "Saint Kitts and Nevis", NameZh: "圣基茨和尼维斯"},
	"KP": {NameEn: "North Korea", NameZh: "朝鲜"},
	"KR": {NameEn: "South Korea", NameZh: "韩国"},
	"KW": {NameEn: "Kuwait", NameZh: "科威特"},
	"KY": {NameEn: "Cayman Islands", NameZh: "开曼群岛"},
	"KZ": {NameEn: "Kazakhstan", NameZh: "哈萨克斯坦"},
	"LA": {NameEn: "Laos", NameZh: "老挝"},
	"LB": {NameEn: "Lebanon", NameZh: "黎巴嫩"},
	"LC": {NameEn: "Saint Lucia", NameZh: "圣卢西亚"},
	"LI": {NameEn: "Liechtenstein", NameZh: "列支敦士登"},
	"LK": {NameEn: "Sri Lanka", NameZh: "斯里兰卡"},
	"LR": {NameEn: "Liberia", NameZh: "利比里亚"},
	"LS": {NameEn: "Lesotho", NameZh: "莱索托"},
	"LT": {NameEn: "Lithuania", NameZh: "立陶宛"},
	"LU": {NameEn: "Luxembourg", NameZh: "卢森堡"},
	"LV": {NameEn: "Latvia", NameZh: "拉脱维亚"},
	"LY": {NameEn: "Libya", NameZh: "利比亚"},
	"MA": {NameEn: "Morocco", NameZh: "摩洛哥"},
	"MC": {NameEn: "Monaco", NameZh: "摩纳哥"},
	"MD": {NameEn: "Moldova", NameZh: "摩尔多瓦"},
	"ME": {NameEn: "Montenegro", NameZh: "黑山"},
	"MF": {NameEn: "Saint Martin", NameZh: "圣马丁"},
	"MG": {NameEn: "Madagascar", NameZh: "马达加斯加"},
	"MH": {NameEn: "Marshall Islands", NameZh: "马绍尔群岛"},
	"MK": {NameEn: "North Macedonia", NameZh: "北馬其頓"},
	"ML": {NameEn: "Mali", NameZh: "马里"},
	"MM": {NameEn: "Myanmar", NameZh: "缅甸"},
	"MN": {NameEn: "Mongolia", NameZh: "蒙古"},
	"MO": {NameEn: "Macau", NameZh: "澳门"},
	"MP": {NameEn: "Northern Mariana Islands", NameZh: "北马里亚纳群岛"},
	"MQ": {NameEn: "Martinique", NameZh: "马提尼克"},
	"MR": {NameEn: "Mauritania", NameZh: "毛里塔尼亚"},
	"MS": {NameEn: "Montserrat", NameZh: "蒙特塞拉特"},
	"MT": {NameEn: "Malta", NameZh: "马耳他"},
	"MU": {NameEn: "Mauritius", NameZh: "毛里求斯"},
	"MV": {NameEn: "Maldives", NameZh: "马尔代夫"},
	"MW": {NameEn: "Malawi", NameZh: "马拉维"},
	"MX": {NameEn: "Mexico", NameZh: "墨西哥"},
	"MY": {NameEn: "Malaysia", NameZh: "马来西亚"},
	"MZ": {NameEn: "Mozambique", NameZh: "莫桑比克"},
	"NA": {NameEn: "Namibia", NameZh: "纳米比亚"},
	"NC": {NameEn: "New Caledonia", NameZh: "新喀里多尼亚"},
	"NE": {NameEn: "Niger", NameZh: "尼日尔"},
	"NF": {NameEn: "Norfolk Island", NameZh: "诺福克岛"},
	"NG": {NameEn: "Nigeria", NameZh: "尼日利亚"},
	"NI": {NameEn: "Nicaragua", NameZh: "尼加拉瓜"},
	"NL": {NameEn: "Netherlands", NameZh: "荷兰"},
	"NO": {NameEn: "Norway", NameZh: "挪威"},
	"NP": {NameEn: "Nepal", NameZh: "尼泊尔"},
	"NR": {NameEn: "Nauru", NameZh: "瑙鲁"},
	"NU": {NameEn: "Niue", NameZh: "纽埃"},
	"NZ": {NameEn: "New Zealand", NameZh: "新西兰"},
	"OM": {NameEn: "Oman", NameZh: "阿曼"},
	"PA": {NameEn: "Panama", NameZh: "巴拿马"},
	"PE": {NameEn: "Peru", NameZh: "秘鲁"},
	"PF": {NameEn: "French Polynesia", NameZh: "法属波利尼西亚"},
	"PG": {NameEn: "Papua New Guinea", NameZh: "巴布亚新几内亚"},
	"PH": {NameEn: "Philippines", NameZh: "菲律宾"},
	"PK": {NameEn: "Pakistan", NameZh: "巴基斯坦"},
	"PL": {NameEn: "Poland", NameZh: "波兰"},
	"PM": {NameEn: "Saint Pierre and Miquelon", NameZh: "圣皮埃尔和密克隆"},
	"PN": {NameEn: "Pitcairn Islands", NameZh: "皮特凯恩群岛"},
	"PR": {NameEn: "Puerto Rico", NameZh: "波多黎各"},
	"PS": {NameEn: "Palestine", NameZh: "巴勒斯坦"},
	"PT": {NameEn: "Portugal", NameZh: "葡萄牙"},
	"PW": {NameEn: "Palau", NameZh: "帕劳"},
	"PY": {NameEn: "Paraguay", NameZh: "巴拉圭"},
	"QA": {NameEn: "Qatar", NameZh: "卡塔尔"},
	"RE": {NameEn: "Reunion", NameZh: "留尼旺岛"},
	"RO": {NameEn: "Romania", NameZh: "罗马尼亚"},
	"RS": {NameEn: "Serbia", NameZh: "塞尔维亚"},
	"RU": {NameEn: "Russia", NameZh: "俄罗斯"},
	"RW": {NameEn: "Rwanda", NameZh: "卢旺达"},
	"SA": {NameEn: "Saudi Arabia", NameZh: "沙特阿拉伯"},
	"SB": {NameEn: "Solomon Islands", NameZh: "所罗门群岛"},
	"SC": {NameEn: "Seychelles", NameZh: "塞舌尔"},
	"SD": {NameEn: "Sudan", NameZh: "苏丹"},
	"SE": {NameEn: "Sweden", NameZh: "瑞典"},
	"SG": {NameEn: "Singapore", NameZh: "新加坡"},
	"SH": {NameEn: "Saint Helena, Ascension and Tristan da Cunha", NameZh: "圣赫勒拿、阿森松和特里斯坦-达库尼亚"},
	"SI": {NameEn: "Slovenia", NameZh: "斯洛文尼亚"},
	"SJ": {NameEn: "Svalbard and Jan Mayen", NameZh: "斯瓦尔巴特"},
	"SK": {NameEn: "Slovakia", NameZh: "斯洛伐克"},
	"SL": {NameEn: "Sierra Leone", NameZh: "塞拉利昂"},
	"SM": {NameEn: "San Marino", NameZh: "圣马力诺"},
	"SN": {NameEn: "Senegal", NameZh: "塞内加尔"},
	"SO": {NameEn: "Somalia", NameZh: "索马里"},
	"SR": {NameEn: "Suriname", NameZh: "苏里南"},
	"SS": {NameEn: "South Sudan", NameZh: "南苏丹"},
	"ST": {NameEn: "Sao Tome and Principe", NameZh: "圣多美和普林西比"},
	"SV": {NameEn: "El Salvador", NameZh: "萨尔瓦多"},
	"SX": {NameEn: "Sint Maarten", NameZh: "圣马丁岛"},
	"SY": {NameEn: "Syria", NameZh: "叙利亚"},
	"SZ": {NameEn: "Eswatini", NameZh: "斯威士兰"},
	"TC": {NameEn: "Turks and Caicos Islands", NameZh: "特克斯和凯科斯群岛"},
	"TD": {NameEn: "Chad", NameZh: "乍得"},
	"TF": {NameEn: "French Southern and Antarctic Lands", NameZh: "法国南部和南极土地"},
	"TG": {NameEn: "Togo", NameZh: "多哥"},
	"TH": {NameEn: "Thailand", NameZh: "泰国"},
	"TJ": {NameEn: "Tajikistan", NameZh: "塔吉克斯坦"},
	"TK": {NameEn: "Tokelau", NameZh: "托克劳"},
	"TL": {NameEn: "Timor-Leste", NameZh: "东帝汶"},
	"TM": {NameEn: "Turkmenistan", NameZh: "土库曼斯坦"},
	"TN": {NameEn: "Tunisia", NameZh: "突尼斯"},
	"TO": {NameEn: "Tonga", NameZh: "汤加"},
	"TR": {NameEn: "Turkiye", NameZh: "土耳其"},
	"TT": {NameEn: "Trinidad and Tobago", NameZh: "特立尼达和多巴哥"},
	"TV": {NameEn: "Tuvalu", NameZh: "图瓦卢"},
	"TW": {NameEn: "Taiwan", NameZh: "台灣"},
	"TZ": {NameEn: "Tanzania", NameZh: "坦桑尼亚"},
	"UA": {NameEn: "Ukraine", NameZh: "乌克兰"},
	"UG": {NameEn: "Uganda", NameZh: "乌干达"},
	"UM": {NameEn: "United States Minor Outlying Islands", NameZh: "美国本土外小岛屿"},
	"US": {NameEn: "United States", NameZh: "美国"},
	"UY": {NameEn: "Uruguay", NameZh: "乌拉圭"},
	"UZ": {NameEn: "Uzbekistan", NameZh: "乌兹别克斯坦"},
	"VA": {NameEn: "Vatican City", NameZh: "梵蒂冈"},
	"VC": {NameEn: "Saint Vincent and the Grenadines", NameZh: "圣文森特和格林纳丁斯"},
	"VE": {NameEn: "Venezuela", NameZh: "委内瑞拉"},
	"VG": {NameEn: "British Virgin Islands", NameZh: "英属维尔京群岛"},
	"VI": {NameEn: "United States Virgin Islands", NameZh: "美属维尔京群岛"},
	"VN": {NameEn: "Vietnam", NameZh: "越南"},
	"VU": {NameEn: "Vanuatu", NameZh: "瓦努阿图"},
	"WF": {NameEn: "Wallis and Futuna", NameZh: "瓦利斯和富图纳群岛"},
	"WS": {NameEn: "Samoa", NameZh: "萨摩亚"},
	"XK": {NameEn: "Kosovo", NameZh: "科索沃"},
	"YE": {NameEn: "Yemen", NameZh: "也门"},
	"YT": {NameEn: "Mayotte", NameZh: "马约特"},
	"ZA": {NameEn: "South Africa", NameZh: "南非"},
	"ZM": {NameEn: "Zambia", NameZh: "赞比亚"},
	"ZW": {NameEn: "Zimbabwe", NameZh: "津巴布韦"},
}
